### PR TITLE
Autocomplete speedup vol. 2 - finishing

### LINKED ISSUE #274: Intellisense slow on 5k files
I like the new auto completion tool and, I have a Laravel project that parses the files like so:

> All 5568 PHP files parsed in 253 seconds. 178 MiB allocated.

When I type `$someVar->` it takes about 2 seconds until the suggestions show up.

### PR DESCRIPTION
**Pull request by MichaelBelgium**
Finishing https://github.com/felixfbecker/php-language-server/pull/599 by merging master and fixing the conflicts.  Although **I wasn't sure which side to pick while merging**, I assumed the side of autocomplet-speedup.

closes #274 
closes #599

### CODE REVIEW

**Comment by felixfbecker** [comment]
@MichaelBelgium unfortunately tests are failing (they passed on the old PR):

```
Error: Call to undefined method LanguageServerProtocol\CompletionItem::fromDefinition()
```

This function was moved to a different class: https://github.com/felixfbecker/php-language-server/blob/master/src/Factory/CompletionItemFactory.php

**Comment by MichaelBelgium** [comment]
> @MichaelBelgium unfortunately tests are failing (they passed on the old PR):
> 
> ```
> Error: Call to undefined method LanguageServerProtocol\CompletionItem::fromDefinition()
> ```
> This function was moved to a different class: https://github.com/felixfbecker/php-language-server/blob/master/src/Factory/CompletionItemFactory.php

Fixed 👌

**Comment by felixfbecker** [comment]
I found a crash when running the language server on this project:

```
CRITICAL  Error: Cannot use object of type LanguageServer\Definition as array in /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php:382
Stack trace:
#0 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php(386): LanguageServer\Index\Index->getIndexValue(Array, Object(LanguageServer\Definition))
#1 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php(151): LanguageServer\Index\Index->getIndexValue(Array, Array)
#2 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/AbstractAggregateIndex.php(137): LanguageServer\Index\Index->getDefinition('->assertSession...', false)
#3 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/AbstractAggregateIndex.php(137): LanguageServer\Index\AbstractAggregateIndex->getDefinition('->assertSession...', false)
#4 /Users/felix/src/github.com/felixfbecker/php-language-server/src/DefinitionResolver.php(772): LanguageServer\Index\AbstractAggregateIndex->getDefinition('->assertSession...')
#5 /Users/felix/src/github.com/felixfbecker/php-language-server/src/DefinitionResolver.php(739): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#6 /Users/felix/src/github.com/felixfbecker/php-language-server/src/DefinitionResolver.php(404): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#7 /Users/felix/src/github.com/felixfbecker/php-language-server/src/DefinitionResolver.php(331): LanguageServer\DefinitionResolver->resolveMemberAccessExpressionNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#8 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(175): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#9 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(124): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#10 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#11 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Expression\CallExpression))
#12 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#13 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#14 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#15 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(140): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\TraitMembers))
#16 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(136): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\Statement\TraitDeclaration))
#17 /Users/felix/src/github.com/felixfbecker/php-language-server/src/TreeAnalyzer.php(58): LanguageServer\TreeAnalyzer->traverse(Object(Microsoft\PhpParser\Node\SourceFileNode))
#18 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n\nnamespac...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///Users/f...')
#19 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\n\nnamespac...')
#20 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///Users/f...', '<?php\n\nnamespac...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#21 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///Users/f...', '<?php\n\nnamespac...')
#22 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#23 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n\nnamespac...')
#24 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n\nnamespac...')
#25 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#26 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#27 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#28 /Users/felix/src/github.com/felixfbecker/php-language-server/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#29 /Users/felix/src/github.com/felixfbecker/php-language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#30 {main}
```

It crashes when indexing `validation/frameworks/drupal/core/tests/Drupal/FunctionalTests/AssertLegacyTrait.php`.

**Comment by felixfbecker** [comment]
Here's another crash that happens when running `./benchmarks/parsing.php`:

```
Fatal error: Uncaught TypeError: Argument 3 passed to LanguageServer\Index\Index::indexDefinition() must be of the type array, object given, called in /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php on line 412 and defined in /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php:398
Stack trace:
#0 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php(412): LanguageServer\Index\Index->indexDefinition(1, Array, Object(LanguageServer\Definition), Object(LanguageServer\Definition))
#1 /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php(175): LanguageServer\Index\Index->indexDefinition(0, Array, Array, Object(LanguageServer\Definition))
#2 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocument.php(158): LanguageServer\Index\Index->setDefinition('->A()', Object(LanguageServer\Definition))
#3 /Users/felix/src/github.com/felixfbecker/php-language-server/src/PhpDocument.php(105): LanguageServer in /Users/felix/src/github.com/felixfbecker/php-language-server/src/Index/Index.php on line 398
```

**Comment by felixfbecker** [comment]
cc @Declspeck

**Pull request merged**
