### PR TITLE
content-limit become configurable

### PR DESCRIPTION
**Pull request by robberphex**
1. add `content-limit` option.
2. do not retrieve content if it's too large

### CODE REVIEW

**Comment by robberphex** [comment]
before:
```
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

[Info  - 11:57:08 PM] 19433 files total
......(Ignored some files because it exceeds size limit)
[Info  - 12:29:09 AM] All 19433 PHP files parsed in 1921 seconds. 657 MiB allocated.
```

after(with limit 150000):
```
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

[Info  - 1:00:55 AM] 19433 files total
......(Ignored some files because it exceeds size limit)
[Info  - 1:32:19 AM] All 19433 PHP files parsed in 1884 seconds. 657 MiB allocated.
```

**Comment by robberphex** [comment]
This solves issues #548 #299

**Comment by markwu** [comment]
Will this feature merge to master?

**Comment by robberphex** [comment]
Excuse me, I'm not working on this, so I will close this PR.

**Comment by markwu** [comment]
@RobberPhex  Will vscode-php-intellisense apply this change and allow me to modify the content limit? 150000 is too small for some cases.

Thanks.

**Comment by robberphex** [comment]
@markwu Thanks for you attention.

But the question of this language server is, the performance isn't good enough.

And there are more than one PR working on content-limit, but I didn't see any response from author.

**Comment by markwu** [comment]
@RobberPhex I see, thanks for your reply.

**Pull request closed without merging**
