### PR TITLE
Update phpunit config

### PR DESCRIPTION
**Pull request by vinkla**
This pull request updates the PHPUnit XML configuration: 

- Added more strict configuration.
- Added coloured output from our tests.
- Don't allow risky tests and warnings.

Happy Hacktoberfest!

### CODE REVIEW

**Comment by felixfbecker** [comment]
Thanks!

**Comment by vinkla** [comment]
@felixfbecker any pointers on how we can fix the risky test?

**Comment by felixfbecker** [comment]
The test is fine, is it possible to add an ignore comment to surpress the error?

**Comment by vinkla** [comment]
> The test is fine, is it possible to add an ignore comment to surpress the error?

I've pushed an fix to ignore risky tests. It should do the job.

**Pull request merged**
