### PR TITLE
Fix crash when returning null instead of a Type when trying to infer node type

### PR DESCRIPTION
**Pull request by Alenore**
Returns a Mixed instead of Null_, as the return type is pretty much unknown.

### CODE REVIEW

**Comment by felixfbecker** [comment]
The return value has a semantic meaning

> Returns null if the node does not have a type.

Only very few nodes have a type.

**Comment by drKnoxy** [comment]
just wanted to say thanks @Alenore my plugin was busted after upgrading from 0.0.12 -> 1.1.3 and this fixed it.

**Comment by felixfbecker** [comment]
@Alenore Are you planning to look into the cause of the issue?

**Comment by Alenore** [comment]
I was especially busy recently but it's still on my todo list, as it directly affects my workflow :)

**Comment by Alenore** [comment]
Apparently was resolved in PR #340

**Pull request closed without merging**
