### PR TITLE
WIP: Append backlash to namespace identifer

### PR DESCRIPTION
**Pull request by ADmad**
Refs #400.

### CODE REVIEW

**Comment by ADmad** [comment]
@felixfbecker I dunno how to fix the 2 tests that are failing. I also haven't been able to figure where the change in required for `Indexer`.

**Comment by felixfbecker** [comment]
It's actually `DefinitionResolver->resolveReferenceNodeToFqn()`, my bad

**Comment by felixfbecker** [comment]
Test is still failing

**Comment by ADmad** [comment]
Yes, I am not sure how to fix that remaining one.

**Pull request closed without merging**
