### PR TITLE
fix(DefinitionResolver): find variables in sibling children

### LINKED ISSUE #566: PHP Intellisense, huge memory leak when building cache
We use vscode and php intellisense with Laravel project and we have a huge memory leak (16 Go in 5 minutes) with this file : **vendor/symfony/http-kernel/DependencyInjection/RegistrerControllerArgumentLocatorsPass.php** during building cache.

If I renamed this file  .OLD , all cache will be built without any problem. If i renamed it .php after the cache is build, all is OK.

My version : 

Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T09:56:48.842Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
PHP Intellisense 2.2.2
Laravel Project

### PR DESCRIPTION
**Pull request by felixfbecker**
Fixes #566

### CODE REVIEW

**Comment by phil-nelson** [comment]
Thanks, this is a better solution that mine, I was struggling to work out how to do something like this as your suggestion.

**Comment by felixfbecker** [comment]
This also includes a change unrelated to the bug, in that before we only checked previous siblings and parents, but not the descendants of those. So this wouldn't register `$foo` before:
```php
if (true) {
  $foo = 123
}
$f| // no completion for $foo
```
now it should.

With that change I could make it so that the search for the foreach key/value starts at the parent/sibling too because it can then traverse into the ForeachStatement, but not if that was the starting point.

**Comment by felixfbecker** [comment]
@jens1o @phil-nelson if anyone wants to test: [php-intellisense-1.5.4.vsix.zip](https://github.com/felixfbecker/php-language-server/files/1592295/php-intellisense-1.5.4.vsix.zip)

**Comment by phil-nelson** [comment]
I've had a play with this branch, no problems so far :thumbsup:

**Comment by jens1o** [comment]
Works liek a charm :)

**Pull request merged**
