### PR TITLE
Go to definition doesn't work for method return type

### LINKED ISSUE #75: Go to definition doesn't work for method return type
Example:
```php
<?php
namespace TestNamespace;

class MyTest
{
    public function abc() : TestClass // it does not work
    {
        new TestClass(); // it works
    }
}
```

### PR DESCRIPTION
**Pull request by mniewrzal**
Closes #75

### CODE REVIEW

**Comment by felixfbecker** [comment]
Adding a new fixture for every bug will become unmanageable. What are your suggestions on improving the tests?

**Comment by MadHed** [comment]
I'm not an expert at unit testing but my gut feeling tells me that a fixture specific to a bug should only be added if the bug appears as the direct result of a corner case in the parsed source code.
For testing normal operation a single shared fixture containing all testable cases should suffice, no?

**Comment by felixfbecker** [comment]
@mniewrzal I'm working on a refactor of the tests which will make it much easier in the future to change fixtures

**Comment by mniewrzal** [comment]
@felixfbecker Ok, nice :)

**Comment by felixfbecker** [comment]
@mniewrzal #87

**Comment by felixfbecker** [comment]
@mniewrzal would you mind rebasing this on the new test structure?

**Comment by mniewrzal** [comment]
I will do this today.

**Comment by felixfbecker** [comment]
Why not use the return type of https://github.com/felixfbecker/php-language-server/blob/master/fixtures/global_references.php#L22 ?

**Comment by mniewrzal** [comment]
Case with function return type was covered earlier - https://github.com/felixfbecker/php-language-server/blob/master/tests/Server/TextDocument/Definition/GlobalTest.php#L141. This is fix for method return type.

**Comment by felixfbecker** [comment]
Okay, sorry. Could you then please just add a return type to one of the methods defined in `symbols.php` so we don't clutter the fixtures with new classes for every new test?

**Comment by mniewrzal** [comment]
Ok

**Comment by mniewrzal** [comment]
Anything I should change or its ready to go? I don't want to resolve conflicts one more time ;)

**Comment by felixfbecker** [comment]
No, looks great :)

**Comment by mniewrzal** [comment]
Cool, thanks for review :)

**Pull request merged**
