### PR TITLE
Update composer.json structure

### PR DESCRIPTION
**Pull request by vinkla**
I've updated the structure of the `composer.json` file:

- Added config to prefer distribution versions of packages.
- Removed the `type` since it defaults to library.
- Renamed `Microsoft` to `microsoft`.
- Sorted the required packages by name.

Let me know what you think and if I should update anything. 

Happy Hacktoberfest!

### CODE REVIEW

**Comment by felixfbecker** [comment]
> Added config to prefer distribution versions of packages

Why that change? It has the disadvantage of not having the dependency in vendor/ be a git repo that can be hacked on

**Comment by vinkla** [comment]
> Why that change? It has the disadvantage of not having the dependency in vendor/ be a git repo that can be hacked on.

I'm not sure what you're referring to. This update shouldn't have a bad impact on the current behaviour.

**Comment by felixfbecker** [comment]
When I run `composer install` in my dev environment, Composer will by default `git clone` every dependency, allowing me to make edits in my `vendor` directory (e.g. on the JSON RPC library), commit and push them there. With `--prefer-dist`, it will download a tarball from GitHub, which I cannot commit in. This makes the workflow a lot worse since Composer doesn't have something like `npm link`. I don't see the need for that configuration to sit in composer.json, if you are in a production environment you can pass `--prefer-dist` to Composer to get the same effect (we do that in Travis)

**Comment by felixfbecker** [comment]
At least here: https://github.com/felixfbecker/vscode-php-intellisense/blob/master/.travis.yml#L17
We should add it in this repo too

**Comment by vinkla** [comment]
I've pushed a fix to remove the distribution configuration.

**Comment by felixfbecker** [comment]
Could you add the `--prefer-dist` in travis.yml?

**Comment by vinkla** [comment]
> Could you add the --prefer-dist in travis.yml?

Sure, I'm working on a pull request for the `.travis.yml` file right now.

**Comment by vinkla** [comment]
> Could you add the --prefer-dist in travis.yml?

Sure, I'm working on a pull request for the `.travis.yml` file right now. Just waiting on this pull request to be completed first.

**Pull request merged**
