### PR TITLE
update composer.json php codesniffer

### PR DESCRIPTION
**Pull request by allan-simon**
it has been released in 3.0.X as stable

### CODE REVIEW

**Comment by felixfbecker** [comment]
Build's broken. There was a problem with the CodeSniffer 3 autoloader. If you can fix that, happy to upgrade

**Comment by raul338** [comment]
You can create a tests/bootstrap.php file and include the autoload there
```php
<?php
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/squizlabs/php_codesniffer/autoload.php';
```

**Comment by felixfbecker** [comment]
That would fix it for tests, but does it fix it at runtime?

**Comment by raul338** [comment]
Can't really tell right now, I'm trying to debug vscode-php-intellisense, after the symlink and press `F5` throws an error:
```
Here is the error stack:  /home/raul/test/vscode-php-intellisense/node_modules/vscode-languageclient/lib/main.js:916
        return this.resolveConnection().theconnection => {
               ^^^^
```
I cloned the master branch

**Comment by felixfbecker** [comment]
That's not a very helpful error stack. Do you have the right version of Node? Did you run `npm install`?

**Comment by raul338** [comment]
I didn't see an error that `npm run build` throws
```
> php-intellisense@1.5.1 build /home/raul/test/vscode-php-intellisense
> tsc -p .

node_modules/vscode-languageclient/lib/client.d.ts(1,706): error TS2305: Module ''vscode'' has no exported member 'WorkspaceFolder'.
node_modules/vscode-languageclient/lib/workspaceFolders.proposed.d.ts(1,10): error TS2305: Module ''vscode'' has no exported member 'WorkspaceFoldersChangeEvent'.
```
I'll keep trying...

**Pull request closed without merging**
