### PR TITLE
Log only to STDERR

### LINKED ISSUE #135: Only log exceptions to STDERR
Currently gets written to both STDOUT and STDERR which messes up with the protocol of course.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #135 

Doesn't work currently:
```
PHP Fatal error:  Maximum function nesting level of '1000' reached, aborting! in C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php on line 60
PHP Stack trace:
PHP   1. Symfony\Component\Debug\ErrorHandler->handleException() C:\Users\felix\git\OpenSource\php-language-server\vendor\symfony\debug\ErrorHandler.php:0
PHP   2. Monolog\Logger->log() C:\Users\felix\git\OpenSource\php-language-server\vendor\symfony\debug\ErrorHandler.php:528
PHP   3. Monolog\Logger->addRecord() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Logger.php:517
PHP   4. Monolog\Handler\AbstractProcessingHandler->handle() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Logger.php:336
PHP   5. Monolog\Formatter\LineFormatter->format() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php:35
PHP   6. Monolog\Formatter\NormalizerFormatter->format() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\LineFormatter.php:68
PHP   7. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:43
PHP   8. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
PHP   9. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
PHP  10. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
PHP  11. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
PHP  12. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
PHP  13. Monolog\Formatter\NormalizerFormatter->normalize() C:\Users\felix\git\OpenSource\php-language-server\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php:82
```
Don't know why.

### CODE REVIEW

**Comment by Seldaek** [comment]
The failure might be due to you passing a recursive array structure as monolog's context info. Looks like it comes from the exception handling though so I am not sure what exactly does it.. Do you have a minimal way to reproduce this so I could try to look what's up in monolog and possibly resolve this?

**Comment by felixfbecker** [comment]
I just added these lines right after the register call:
```php
$arr = [];
echo $arr['undefined'];
```
causes an undefined index notice, which triggers the error handler.

What exactly do you mean with recursive array?

**Comment by felixfbecker** [comment]
Help would be greatly appreciated

**Comment by Seldaek** [comment]
I checked out the branch, added those two lines after ErrorHandler::register() in bin/php-language-server.php but I don't get any output when I run that file, and no error when I run phpunit... Not sure how you got this to fail?

**Comment by Seldaek** [comment]
Ah nevermind sorry I forgot I had xdebug disabled in my 7.1RC6.. I can reproduce it on 7.0 - will investigate.

**Comment by Seldaek** [comment]
OK that was really nasty. I pushed a fix to symfony to avoid the problem you hit (see ref above). That said, everything should work fine as long as you avoid errors on the top level.

Try doing this instead:

```
function testLog() {
    $arr=[];
    echo $arr['undefined'];
}
testLog();
```

Then it should not recurse endlessly anymore and you can check that it works.

**Comment by felixfbecker** [comment]
Thanks a lot! Can you notify me when it is released?

**Comment by Seldaek** [comment]
Well it'll be included in the next patch release, but to be honest as I said this only happens if an error occurs in the global scope which is highly unlikely in reality, so I'd say go ahead and merge this already, I wouldn't wait on a symfony release.

**Comment by felixfbecker** [comment]
Okay - if my usage is otherwise correct, I will merge. Thanks!

**Comment by felixfbecker** [comment]
Unfortunately, the actual issue is not solved - the errors are logged to STDERR, but the fatal error that is triggered by the uncaught exception is logged to STDOUT:

image

The output also is super ugly now as for some reason the exception becomes JSON-encoded instead of casted to a string with human-readable stack. Any idea? The symfony ExceptionHandler class does not have a `setDefaultLogger` method

**Pull request closed without merging**
