### PR TITLE
Support type hinting

### PR DESCRIPTION
**Pull request by jens1o**
This pr does include the pr #374, because the pr was created with the master branch. So I would like that the "define-constants" pr will be merged first.

### CODE REVIEW

**Comment by jens1o** [comment]
When fine, I'll create tests. But I'm unsure wether the code is okay like this.

**Comment by swiffer** [comment]
@felixfbecker is this still working, would be great to have this merged?

should solve issue #350 right?

**Comment by felixfbecker** [comment]
This is based on an old version of the langserver that used a different parser, see the merge conflicts. It's also missing some tests.

**Comment by jens1o** [comment]
Okay, ehm, I will watch out when I got more time and then refile the pull request.

**Pull request closed without merging**
