### PR TITLE
Bump tolerant-php-parser

### PR DESCRIPTION
**Pull request by roblourens**
Shouldn't ^0.0.2 install 0.0.3?

### CODE REVIEW

**Comment by jrobeson** [comment]
@roblourens : not for 0.0.x versions, only 0.x.y

**Comment by felixfbecker** [comment]
@jrobeson are you sure? At least npm will install 0.0.3 for ^0.0.2 (but not 0.1.0)

**Comment by felixfbecker** [comment]
build is failing, there seems to be an incorrect assertion

**Comment by jrobeson** [comment]
pretty sure.

**Comment by felixfbecker** [comment]
confirmed

**Comment by jrobeson** [comment]
My assertion is actually wrong, as it applies just as well for other 0.x.y releases too. It's when it gets to 1.x.y that it starts acting normally.


> The ^ operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example ^1.2.3 is equivalent to >=1.2.3 <2.0.0 as none of the releases until 2.0 should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.

**Pull request merged**
