### PR TITLE
Tolerate $this usage in anonymous functions

### PR DESCRIPTION
**Pull request by alWerewolf**
Alternative solution for issue #536.
For $this var usage it gives warning
>$this might not be bound by invoker of callable or might be bound to object of any class. Consider adding instance class check.

And hints developer to check class of $this before usage.
Class check can be added in form 
```php
if ($this instanceof [class])" {
    /*use $this*/
}
```
Note: if class check added no type checking is done in language server it just hides the warning.
There is a leaf in code marked by comment:
> //else we should warn here that invoker can bind $this to object of any class. Should we?

Question in comment is for community.

### CODE REVIEW

**Comment by felixfbecker** [comment]
I've never seen anyone use `if $this instanceof` so I don't think anyone would actually use that. I don't think it belongs into the language server.

**Comment by jens1o** [comment]
@felixfbecker Here you go: https://github.com/pmmp/PocketMine-MP/blob/1f5f67e08712078588ef2241d870a0712b7a0cf4/src/pocketmine/block/Liquid.php#L182-L190

**Comment by alWerewolf** [comment]
$this can be bound to ANY object by caller of Closure(anonymous function) so we must warn about it.
It's all about developer must know for sure how his function is called and which object is bound.
Class check for $this var must ensure expected results.
Anyone can suggest their way to do class check. I think there are many ways.
I've choosen $this instanceof because of simplicity and it's favor vs deprecated is_a.
I thought of example where you pass your anonymous function to "blackbox".
You never know for sure how it's called so checking $this var will help from getting into trouble.

**Comment by felixfbecker** [comment]
I decided for disabling the warnings in these cases instead. This is similar to what e.g. TypeScript does - `this` is `any` by default, so no checks. Only in cases where it is known to be a certain type (or type hinted) should we do warnings. In the future, we can give the user the option to type hint `$this`, but until then we should force the user to write code to circumvent the warning.

**Pull request closed without merging**
